name: Publish to DockerHub

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t permguard/all-in-one:latest -f ./cmd/server-all-in-one/Dockerfile .

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Tag Docker Image
        run: |
          IMAGE_TAG="${VERSION}"
          docker tag permguard/all-in-one:latest permguard/all-in-one:$IMAGE_TAG
          docker push permguard/all-in-one:$IMAGE_TAG

      - name: Push Docker Image
        run: |
          docker push permguard/all-in-one:latest
