name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t permguard/all-in-one:latest -f ./cmd/server-all-in-one/Dockerfile .

      - name: Tag Docker Image
        run: |
          IMAGE_TAG=0.0.0.$(git rev-list --count HEAD)
          docker tag permguard/all-in-one:latest permguard/all-in-one:$IMAGE_TAG
          docker push permguard/all-in-one:$IMAGE_TAG

      - name: Push Docker Image
        run: |
          docker push permguard/all-in-one:latest
